from setuptools import setup, find_packages

with open("README.md", encoding="utf-8") as f:
    long_description = f.read()

setup(
    name="pytigon-lib",
    version="0.260511",
    description="Pytigon library — Python/Django application framework with multi-format rendering and indentation-based HTML preprocessor",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Slawomir Cholaj",
    author_email="slawomir.cholaj@gmail.com",
    license="LGPLv3",
    packages=find_packages(),
    package_data={
        "pytigon_lib": [
            "schhtml/icss/wiki.icss",
        ],
    },
    include_package_data=True,
    python_requires=">=3.8",
    install_requires=[
        "Django>=3.2",
        "django-environ>=0.10",
        "lxml>=4.6",
        "fs>=2.4",
        "httpx>=0.20",
        "cryptography>=3.4",
        "fpdf2>=2.5",
        "Pillow>=9.0",
        "python-docx>=0.8",
        "xlsxwriter>=3.0",
        "openpyxl>=3.0",
        "markdown>=3.3",
        "pyquery>=1.4",
        "python-dateutil>=2.8",
        "autobahn>=22.0",
    ],
    extras_require={
        "spreadsheet": [
            "pyexcel>=0.7",
            "pyexcel-xlsx>=0.6",
            "pyexcel-ods3>=0.6",
        ],
        "llvm": ["llvmlite>=0.40"],
        "plotting": ["plotly>=5.0", "numpy>=1.20"],
        "pscript": ["pscript>=0.7"],
        "svg": ["svglib>=1.1"],
        "dev": ["ruff>=0.3", "pytest>=7.0", "pytest-django>=4.5"],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
